GH Actions: select GoogleTest version based on C++ standard
If we always use [GoogleTest
v1.14.0](https://github.com/google/googletest/releases/tag/v1.14.0)
(which declares that it requires at least C++14) even for
`-DCMAKE_CXX_STANDARD=98`, then only `kaitaistream.cpp` gets a
`-std=c++98` option, while `unittest.cpp` is compiled under
`-std=c++14`. This is a problem, because then neither
`tests/unittest.cpp` nor `kaitai/kaitaistream.h` included from
`tests/unittest.cpp` know that the `kaitaistream` library was compiled
without C++11 support and try to use it, which doesn't work. Not to
mention that such mixing of C++ standards doesn't make much sense if we
want to verify that we are compatible with a particular version of the
C++ standard.

diff --git a/.build/install-gtest b/.build/install-gtest
--- a/.build/install-gtest
+++ b/.build/install-gtest
@@ -5,7 +5,53 @@ set -ef
 #
 # See https://github.com/google/googletest/blob/d83fee138a9ae6cb7c03688a2d08d4043a39815d/googletest/README.md#build-with-cmake
 
-gtest_version_tag=v1.14.0
+# https://unix.stackexchange.com/a/706411
+script_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
+
+usage()
+{
+	echo "Usage: $0 <cpp-standard>"
+	echo
+	echo '  <cpp-standard>  C++ standard to target (supported: 98, 11, 14 and higher)'
+}
+
+die()
+{
+	printf '%s\n' "$1" >&2
+	printf '\n%s\n' "$(usage)" >&2
+	exit 1
+}
+
+cpp_standard=$1
+if [ -z "$cpp_standard" ]; then
+	die 'Error: <cpp-standard> must not be empty'
+fi
+
+case $cpp_standard in
+	98)
+		# GoogleTest v1.8.1 seems to be the last version supporting C++98,
+		# see https://github.com/google/googletest/releases/tag/release-1.8.1
+		gtest_version_tag=release-1.8.1
+		;;
+	11)
+		# GoogleTest v1.12.1 seems to be the last version supporting C++11,
+		# see https://github.com/google/googletest/releases/tag/release-1.12.1
+		gtest_version_tag=release-1.12.1
+		;;
+	*)
+		if [ "$cpp_standard" -ge 14 ]; then
+			# GoogleTest v1.16.0 (the latest version at the time of writing) requires at
+			# least C++14, see https://github.com/google/googletest/releases/tag/v1.16.0
+			gtest_version_tag=v1.16.0
+		else
+			echo "Error: unsupported value $1 of <cpp-standard>" >&2
+			printf '\n%s\n' "$(usage)" >&2
+			exit 1
+		fi
+		;;
+esac
+
+echo "Installing GoogleTest $gtest_version_tag"
 
 temp_dir=$(mktemp -d)
 cleanup()
@@ -20,6 +66,11 @@ trap 'cleanup' INT TERM HUP EXIT
 # Download
 git clone --depth 1 -b "$gtest_version_tag" -- https://github.com/google/googletest.git "$temp_dir"
 cd -- "$temp_dir"
+if [ "$gtest_version_tag" = release-1.8.1 ]; then
+	# We must apply a patch to fix `-Werror=maybe-uninitialized` (see
+	# https://github.com/google/googletest/issues/3219), otherwise it won't compile
+	git apply -- "$script_dir"/gtest-v1.8.1-fix-Werror-maybe-uninitialized.patch
+fi
 mkdir build
 cd build
 # Configure - build only GoogleTest, not GoogleMock
